name: Vacancy Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 AM (Adjust as needed)
  workflow_dispatch:     # For manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install puppeteer fs
      - run: node vacancy_scraper.js
      - uses: actions/upload-artifact@v4
        with:
          name: vacancies
          path: vacancies.csv
      - uses: actions/upload-artifact@v4
        if: failure() # Only upload on failure
        with:
          name: error-screenshot
          path: error_screenshot.png
