name: Vacancy Scraper

on:
  schedule:
    - cron: '0 8 * * *'  # Run daily at 8:00 AM (Adjust as needed)
  workflow_dispatch:     # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install axios cheerio json2csv
      - run: node vacancy_scraper.js
      - uses: actions/upload-artifact@v3
        with:
          name: vacancies
          path: vacancies.csv